# Generated by Django 5.1.4 on 2024-12-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_ru',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_ru',
        ),
    ]
