# Generated by Django 5.1.4 on 2024-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_category_category_name_en_category_category_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name_ru',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
